<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <ProjectReference Include="../../src/Dmx.Hosting/Dmx.Hosting.csproj" />
    <ProjectReference Include="../../src/Dmx.Patch/Dmx.Patch.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../samples/**/*" LinkBase="samples" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
