<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <ProjectReference Include="../Dmx.UI.Controls/Dmx.UI.Controls.csproj" />
    <ProjectReference Include="../Dmx.Hosting/Dmx.Hosting.csproj" />
    <ProjectReference Include="../Dmx.Fixtures/Dmx.Fixtures.csproj" />
    <ProjectReference Include="../Dmx.Patch/Dmx.Patch.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dmx.UI.Tests" />
  </ItemGroup>

</Project>
