<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Dmx.Core/Dmx.Core.csproj" />
    <ProjectReference Include="../Dmx.Persistence/Dmx.Persistence.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dmx.Fixtures.Tests" />
  </ItemGroup>

</Project>
