<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Luxia.Core/Luxia.Core.csproj" />
    <ProjectReference Include="../Luxia.Persistence/Luxia.Persistence.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxia.Fixtures.Tests" />
  </ItemGroup>

</Project>
