<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <ProjectReference Include="../../src/Dmx.Fixtures/Dmx.Fixtures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="assets/**/*" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../samples/Bibliothèque/**/*" LinkBase="samples/Bibliothèque" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
