<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Luxia.Core/Luxia.Core.csproj" />
    <ProjectReference Include="../Luxia.Messaging/Luxia.Messaging.csproj" />
    <ProjectReference Include="../Luxia.Persistence/Luxia.Persistence.csproj" />
    <ProjectReference Include="../Luxia.Engine/Luxia.Engine.csproj" />
    <ProjectReference Include="../Luxia.Scenes/Luxia.Scenes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Luxia.Show.Tests" />
  </ItemGroup>

</Project>
