<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>DMX</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <ProjectReference Include="../Dmx.Core/Dmx.Core.csproj" />
    <ProjectReference Include="../Dmx.Messaging/Dmx.Messaging.csproj" />
    <ProjectReference Include="../Dmx.Engine/Dmx.Engine.csproj" />
    <ProjectReference Include="../Dmx.Output/Dmx.Output.csproj" />
    <ProjectReference Include="../Dmx.Persistence/Dmx.Persistence.csproj" />
    <ProjectReference Include="../Dmx.Hosting/Dmx.Hosting.csproj" />
    <ProjectReference Include="../Dmx.UI.Controls/Dmx.UI.Controls.csproj" />
    <ProjectReference Include="../Dmx.UI.Modules.Outputs/Dmx.UI.Modules.Outputs.csproj" />
    <ProjectReference Include="../Dmx.UI.Modules.Console/Dmx.UI.Modules.Console.csproj" />
    <ProjectReference Include="../Dmx.UI.Modules.Library/Dmx.UI.Modules.Library.csproj" />
  </ItemGroup>

</Project>
