<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>luxia-headless</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Luxia.Hosting/Luxia.Hosting.csproj" />
    <ProjectReference Include="../../src/Luxia.Audio/Luxia.Audio.csproj" />
  </ItemGroup>

</Project>
