<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <ProjectReference Include="../../src/Luxia.Core/Luxia.Core.csproj" />
    <ProjectReference Include="../../src/Luxia.Messaging/Luxia.Messaging.csproj" />
    <ProjectReference Include="../../src/Luxia.Engine/Luxia.Engine.csproj" />
    <ProjectReference Include="../../src/Luxia.Show/Luxia.Show.csproj" />
    <ProjectReference Include="../../src/Luxia.Output/Luxia.Output.csproj" />
    <ProjectReference Include="../../src/Luxia.Persistence/Luxia.Persistence.csproj" />
    <ProjectReference Include="../../src/Luxia.Hosting/Luxia.Hosting.csproj" />
    <ProjectReference Include="../../src/Luxia.Fixtures/Luxia.Fixtures.csproj" />
    <ProjectReference Include="../../src/Luxia.Patch/Luxia.Patch.csproj" />
    <ProjectReference Include="../../src/Luxia.Scenes/Luxia.Scenes.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Console/Luxia.UI.Modules.Console.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Outputs/Luxia.UI.Modules.Outputs.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Library/Luxia.UI.Modules.Library.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Installation/Luxia.UI.Modules.Installation.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Simulator/Luxia.UI.Modules.Simulator.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Scenes/Luxia.UI.Modules.Scenes.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Live/Luxia.UI.Modules.Live.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Control/Luxia.UI.Modules.Control.csproj" />
    <ProjectReference Include="../../src/Luxia.UI.Modules.Audio/Luxia.UI.Modules.Audio.csproj" />
    <ProjectReference Include="../../src/Luxia.Audio/Luxia.Audio.csproj" />
    <ProjectReference Include="../../src/Luxia.Music/Luxia.Music.csproj" />
    <ProjectReference Include="../../src/Luxia.Music.Enrichment/Luxia.Music.Enrichment.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
